### ISSUE TITLE
SqlMultiDacpacDeployment does not work when only one DACPAC to deploy

### ISSUE THREAD

**Issue by asiffermann** [geeklearningio/gl-vsts-tasks-azure#7]
Build Log:
```
2016-09-11T19:58:42.3648616Z ##[debug]DACPAC files with version:
2016-09-11T19:58:42.3804883Z ##[debug] Version: 0.1.0.32772 Path: C:\agent\_work\r1\a\Server - Develop CI\Packages\Database\bin\Release\SuccessfulDeploymentPipeline.Database.dacpac
2016-09-11T19:58:42.3804883Z ##[debug]GET http://whatismyip.org/ with 0-byte payload
2016-09-11T19:58:42.5367382Z ##[debug]received 3720-byte response of content type text/html
2016-09-11T19:58:42.5679877Z ##[debug]Agent IP Addresses:
2016-09-11T19:58:42.5679877Z ##[debug] Start IP: 52.166.142.231
2016-09-11T19:58:42.5836129Z ##[debug] End IP: 52.166.142.231
2016-09-11T19:58:42.5992381Z ##[debug][Azure Call] Getting resource details for resource: galo-edge with resource type: Microsoft.Sql/servers
2016-09-11T19:58:43.8886178Z ##[debug][Azure Call] Retrieved resource details successfully for resource: galo-edge with resource type: Microsoft.Sql/servers
2016-09-11T19:58:43.8886178Z ##[debug]Resource Group Name for 'galo-edge' of type 'Microsoft.Sql/servers': 'Galo-Edge'.
2016-09-11T19:58:43.9042427Z ##[debug][Azure Call] Creating firewall rule 6b0eda47-9fb7-47af-8f7b-0674c5a59129 on Azure SQL Server: galo-edge
2016-09-11T19:58:45.5549990Z ##[debug][Azure Call] Firewall rule 6b0eda47-9fb7-47af-8f7b-0674c5a59129 created on Azure SQL Server: galo-edge
2016-09-11T19:58:45.5706233Z ##[debug]Add Azure SQL Database Server Firewall Rule:
2016-09-11T19:58:45.5706233Z ##[debug] IsConfigured: True
2016-09-11T19:58:45.5706233Z ##[debug] RuleName: 6b0eda47-9fb7-47af-8f7b-0674c5a59129
2016-09-11T19:58:45.5706233Z ##[debug][SQL Call] Retrieving SuccessfulDeploymentPipeline-Int DAC Version Number...
2016-09-11T19:58:45.7431442Z ##[debug][SQL Call] SuccessfulDeploymentPipeline-Int DAC Version Number retrieved: 0.0.0.0
2016-09-11T19:58:45.7581316Z ##[debug][Azure Call] Getting resource details for resource: galo-edge with resource type: Microsoft.Sql/servers
2016-09-11T19:58:45.8050285Z ##[debug][Azure Call] Retrieved resource details successfully for resource: galo-edge with resource type: Microsoft.Sql/servers
2016-09-11T19:58:45.8206253Z ##[debug]Resource Group Name for 'galo-edge' of type 'Microsoft.Sql/servers': 'Galo-Edge'.
2016-09-11T19:58:45.8206253Z ##[debug][Azure Call] Deleting firewall rule 6b0eda47-9fb7-47af-8f7b-0674c5a59129 on Azure SQL Server: galo-edge
2016-09-11T19:58:46.6198542Z ##[debug][Azure Call] Firewall rule 6b0eda47-9fb7-47af-8f7b-0674c5a59129 deleted on Azure SQL Server: galo-edge
2016-09-11T19:58:46.6198542Z ##[debug]Leaving C:\agent\_work\_tasks\SqlMultiDacpacDeployment_fc7c81bb-92a2-4750-a0c9-d0d88c749ac0\1.2.0\SqlMultiDacpacDeployment.ps1.
2016-09-11T19:58:46.6198542Z ##[debug]Caught exception from task script.
2016-09-11T19:58:46.6198542Z ##[debug]Error record:
2016-09-11T19:58:46.6979847Z ##[debug]C:\agent\_work\_tasks\SqlMultiDacpacDeployment_fc7c81bb-92a2-4750-a0c9-d0d88c749ac0\1.2.0\SqlMultiDacpacDeployment.ps1 : Method invocation failed because [System.Collections.DictionaryEntry] does not contain a method named 'GetEnumerator'.
2016-09-11T19:58:46.6979847Z ##[debug]At line:1 char:1
2016-09-11T19:58:46.6979847Z ##[debug]+ . 'C:\agent\_work\_tasks\SqlMultiDacpacDeployment_fc7c81bb-92a2-4750- ...
2016-09-11T19:58:46.6979847Z ##[debug]+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2016-09-11T19:58:46.6979847Z ##[debug]    + CategoryInfo          : InvalidOperation: (:) [SqlMultiDacpacDeployment.ps1], RuntimeException
2016-09-11T19:58:46.7136098Z ##[debug]    + FullyQualifiedErrorId : MethodNotFound,SqlMultiDacpacDeployment.ps1
2016-09-11T19:58:46.7136098Z ##[debug] 
2016-09-11T19:58:46.7136098Z ##[debug]Script stack trace:
2016-09-11T19:58:46.7136098Z ##[debug]at <ScriptBlock>, C:\agent\_work\_tasks\SqlMultiDacpacDeployment_fc7c81bb-92a2-4750-a0c9-d0d88c749ac0\1.2.0\SqlMultiDacpacDeployment.ps1: line 62
2016-09-11T19:58:46.7136098Z ##[debug]at <ScriptBlock>, <No file>: line 1
2016-09-11T19:58:46.7136098Z ##[debug]at <ScriptBlock>, <No file>: line 22
2016-09-11T19:58:46.7292347Z ##[debug]at <ScriptBlock>, <No file>: line 18
2016-09-11T19:58:46.7292347Z ##[debug]at <ScriptBlock>, <No file>: line 1
2016-09-11T19:58:46.7292347Z ##[debug]Exception:
2016-09-11T19:58:46.7292347Z ##[debug]System.Management.Automation.RuntimeException: Method invocation failed because [System.Collections.DictionaryEntry] does not contain a method named 'GetEnumerator'.
2016-09-11T19:58:46.7292347Z ##[debug]   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
2016-09-11T19:58:46.7292347Z ##[debug]   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
2016-09-11T19:58:46.7292347Z ##[debug]   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
2016-09-11T19:58:46.7292347Z ##[debug]   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
2016-09-11T19:58:46.7292347Z ##[debug]   at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)
2016-09-11T19:58:46.7292347Z ##[debug]   at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)
2016-09-11T19:58:46.7292347Z ##[debug]   at System.Management.Automation.PSScriptCmdlet.RunClause(Action`1 clause, Object dollarUnderbar, Object inputToProcess)
2016-09-11T19:58:46.7292347Z ##[debug]   at System.Management.Automation.PSScriptCmdlet.DoEndProcessing()
2016-09-11T19:58:46.7448594Z ##[debug]   at System.Management.Automation.CommandProcessorBase.Complete()
2016-09-11T19:58:46.7448594Z ##[debug]Processing: ##vso[task.logissue type=error]Method invocation failed because [System.Collections.DictionaryEntry] does not contain a method named 'GetEnumerator'.
2016-09-11T19:58:46.7604850Z ##[error]Method invocation failed because [System.Collections.DictionaryEntry] does not contain a method named 'GetEnumerator'.
2016-09-11T19:58:46.7604850Z ##[debug]Processing: ##vso[task.complete result=Failed]
2016-09-11T19:58:46.7917342Z ##[section]Finishing: Deploy Azure SQL DACPAC: $(System.DefaultWorkingDirectory)/**/Database/**/*.dacpac
```

The line 62 of `SqlMultiDacpacDeployment.ps1` produces the error when there is only one DACPAC file to test for the deployment:
``` powershell
$dacFilesToDeploy = $dacFilesWithVersion.GetEnumerator() | Where-Object {$_.Name -gt $databaseVersion}
```

When there is multiple DACPAC files, the type of `$dacFilesWithVersion` is `System.Object[]`, but when there is only one file, it is `System.Collections.DictionaryEntry`.

Should be fix with line 51 replaced with:
`$dacFilesWithVersion = [Array](Get-DacpacVersions -dacpacFilePaths $dacpacFilePaths)`

**Comment by asiffermann** [comment]
Leave opened since it is not yet deployed on the Marketplace (waiting for AzCopy task)

**Comment by sandorfr** [comment]
@asiffermann thanks to last BuildScripts update you can publish updates without azcopy being made public. :tada:

**Comment by asiffermann** [comment]
Released fix with https://github.com/geeklearningio/gl-vsts-tasks-azure/releases/tag/1.2.1
