### ISSUE TITLE
Cannot start/stop slots

### ISSUE THREAD

**Issue by ittennull** [geeklearningio/gl-vsts-tasks-azure#8]
I'm getting this error
```
2016-09-28T05:46:21.7164301Z ##[debug]Resource Group Name for 'myname' of type 'Microsoft.Web/sites': 'devel_rg'.
2016-09-28T05:46:21.7214278Z ##[debug][Azure Call] Stopping slot: myname / develop
2016-09-28T05:46:22.3312246Z ##[debug]Error record:
2016-09-28T05:46:22.4282245Z ##[debug]Stop-AzureRmWebAppSlot : The Resource 'Microsoft.Web/sites/myname/slots/develop' under resource group 'devel_rg' was not found.
2016-09-28T05:46:22.4302266Z ##[debug]At C:\a\_tasks\StopWebApp_a3f35bb6-5341-413a-8091-10f93d390bb5\1.2.1999\StopWebApp.ps1:24 char:19
2016-09-28T05:46:22.4322253Z ##[debug]+         $result = Stop-AzureRmWebAppSlot -ResourceGroupName $resourceGroupName - ...
2016-09-28T05:46:22.4342249Z ##[debug]+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2016-09-28T05:46:22.4352252Z ##[debug]    + CategoryInfo          : CloseError: (:) [Stop-AzureRmWebAppSlot], CloudException
2016-09-28T05:46:22.4372257Z ##[debug]    + FullyQualifiedErrorId : Microsoft.Azure.Commands.WebApps.Cmdlets.DeploymentSlots.StopAzureWebAppSlotCmdlet
2016-09-28T05:46:22.4392252Z ##[debug] 
2016-09-28T05:46:22.4422239Z ##[debug]Script stack trace:
2016-09-28T05:46:22.4472254Z ##[debug]at <ScriptBlock>, C:\a\_tasks\StopWebApp_a3f35bb6-5341-413a-8091-10f93d390bb5\1.2.1999\StopWebApp.ps1: line 24
2016-09-28T05:46:22.4492245Z ##[debug]at <ScriptBlock>, <No file>: line 1
2016-09-28T05:46:22.4512267Z ##[debug]at <ScriptBlock>, <No file>: line 22
2016-09-28T05:46:22.4522314Z ##[debug]at <ScriptBlock>, <No file>: line 18
2016-09-28T05:46:22.4542257Z ##[debug]at <ScriptBlock>, <No file>: line 1
2016-09-28T05:46:22.4572313Z ##[debug]Exception:
2016-09-28T05:46:22.4812251Z ##[debug]Microsoft.Rest.Azure.CloudException: The Resource 'Microsoft.Web/sites/myname/slots/develop' under resource group 'devel_rg' was not found.
2016-09-28T05:46:22.4832235Z ##[debug]   at Microsoft.Azure.Management.WebSites.SitesOperations.<StopSiteSlotWithHttpMessagesAsync>d__153.MoveNext()
2016-09-28T05:46:22.4842273Z ##[debug]--- End of stack trace from previous location where exception was thrown ---
2016-09-28T05:46:22.4862231Z ##[debug]   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
2016-09-28T05:46:22.4872269Z ##[debug]   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2016-09-28T05:46:22.4892250Z ##[debug]   at Microsoft.Azure.Management.WebSites.SitesOperationsExtensions.<StopSiteSlotAsync>d__297.MoveNext()
2016-09-28T05:46:22.4902270Z ##[debug]--- End of stack trace from previous location where exception was thrown ---
2016-09-28T05:46:22.4922266Z ##[debug]   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
2016-09-28T05:46:22.4942246Z ##[debug]   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2016-09-28T05:46:22.4952271Z ##[debug]   at Microsoft.Azure.Management.WebSites.SitesOperationsExtensions.StopSiteSlot(ISitesOperations operations, String resourceGroupName, String name, String slot)
2016-09-28T05:46:22.4972243Z ##[debug]   at Microsoft.Azure.Commands.WebApps.Utilities.WebsitesClient.StopWebApp(String resourceGroupName, String webSiteName, String slotName)
2016-09-28T05:46:22.4982250Z ##[debug]   at Microsoft.Azure.Commands.WebApps.Cmdlets.DeploymentSlots.StopAzureWebAppSlotCmdlet.ExecuteCmdlet()
2016-09-28T05:46:22.5002266Z ##[debug]   at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
2016-09-28T05:46:22.5252239Z ##[debug]Processing: ##vso[task.logissue type=error]The Resource 'Microsoft.Web/sites/myname/slots/develop' under resource group 'devel_rg' was not found.
2016-09-28T05:46:22.5342313Z ##[error]The Resource 'Microsoft.Web/sites/myname/slots/develop' under resource group 'devel_rg' was not found.
2016-09-28T05:46:22.5342313Z ##[debug][Azure Call] Slot stopped: myname / develop
2016-09-28T05:46:22.5502259Z ##[debug]Leaving C:\a\_tasks\StopWebApp_a3f35bb6-5341-413a-8091-10f93d390bb5\1.2.1999\StopWebApp.ps1.
2016-09-28T05:46:22.5562238Z ##[debug]Caught exception from task script.
2016-09-28T05:46:22.5592254Z ##[debug]Error record:
2016-09-28T05:46:22.5732243Z ##[debug]C:\a\_tasks\StopWebApp_a3f35bb6-5341-413a-8091-10f93d390bb5\1.2.1999\StopWebApp.ps1 : Cannot index into a null array.
2016-09-28T05:46:22.5752244Z ##[debug]At line:1 char:1
2016-09-28T05:46:22.5772243Z ##[debug]+ . 'C:\a\_tasks\StopWebApp_a3f35bb6-5341-413a-8091-10f93d390bb5\1.2.1999\StopWebA ...
2016-09-28T05:46:22.5806325Z ##[debug]+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2016-09-28T05:46:22.5822250Z ##[debug]    + CategoryInfo          : InvalidOperation: (:) [StopWebApp.ps1], RuntimeException
2016-09-28T05:46:22.5842269Z ##[debug]    + FullyQualifiedErrorId : NullArray,StopWebApp.ps1
2016-09-28T05:46:22.5852257Z ##[debug] 
2016-09-28T05:46:22.5882252Z ##[debug]Script stack trace:
2016-09-28T05:46:22.5912253Z ##[debug]at <ScriptBlock>, C:\a\_tasks\StopWebApp_a3f35bb6-5341-413a-8091-10f93d390bb5\1.2.1999\StopWebApp.ps1: line 35
2016-09-28T05:46:22.5932253Z ##[debug]at <ScriptBlock>, <No file>: line 1
2016-09-28T05:46:22.5952258Z ##[debug]at <ScriptBlock>, <No file>: line 22
2016-09-28T05:46:22.5962254Z ##[debug]at <ScriptBlock>, <No file>: line 18
2016-09-28T05:46:22.5982252Z ##[debug]at <ScriptBlock>, <No file>: line 1
2016-09-28T05:46:22.6012241Z ##[debug]Exception:
2016-09-28T05:46:22.6152250Z ##[debug]System.Management.Automation.RuntimeException: Cannot index into a null array.
2016-09-28T05:46:22.6172254Z ##[debug]   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
2016-09-28T05:46:22.6192257Z ##[debug]   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
2016-09-28T05:46:22.6202253Z ##[debug]   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
2016-09-28T05:46:22.6222273Z ##[debug]   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
2016-09-28T05:46:22.6232252Z ##[debug]   at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)
2016-09-28T05:46:22.6252250Z ##[debug]   at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)
2016-09-28T05:46:22.6262251Z ##[debug]   at System.Management.Automation.PSScriptCmdlet.RunClause(Action`1 clause, Object dollarUnderbar, Object inputToProcess)
2016-09-28T05:46:22.6282241Z ##[debug]   at System.Management.Automation.PSScriptCmdlet.DoEndProcessing()
2016-09-28T05:46:22.6302274Z ##[debug]   at System.Management.Automation.CommandProcessorBase.Complete()
2016-09-28T05:46:22.6332246Z ##[debug]Processing: ##vso[task.logissue type=error]Cannot index into a null array.
2016-09-28T05:46:22.6332246Z ##[error]Cannot index into a null array.
```

I'm not sure but probably it's because of this line 
`$result = Stop-AzureRmWebAppSlot -ResourceGroupName $resourceGroupName -Name $WebAppName -Slot $Slot -Verbose`
The documentation says that you need to get the value for parameter -Slot from function Get-AzureRMWebAppSlot (https://msdn.microsoft.com/en-us/library/mt652491.aspx)
And there is no Get-AzureRMWebAppSlot anywhere in the code

**Comment by asiffermann** [comment]
Hi @ittennull, and thank you for reporting this issue!

The documentation for `Stop-AzureRMWebAppSlot` says that you have to pass the -Slot parameter as a string, so we just give the cmdlet the name of the slot from the task's parameters.
It works fine as is for us (we are using our tasks every day in several projects).

Thanks to your log, we can see that the WebApp 'myname' is correctly found under the Resource Group 'devel_rg' (I assume you changed the name for privacy concerns). But the following exception is thrown just like there is no slot 'develop' in this WebApp.

Sorry if it sounds a little bit obvious, but are you absolutely sure that you have a Deployment Slot called 'develop' in your WebApp 'myname' ?

**Comment by ittennull** [comment]
Hi @asiffermann ,
thanks for your answer

I used these stop/start tasks from the moment they appeared in VSTS and everything was ok but I didn't use slots - now I do.
I have a site that is deployed to a slot and I stop the slot before deploying to it and then start it again, so my tasks are as follow
![image](https://cloud.githubusercontent.com/assets/510086/18908125/af74222e-856e-11e6-8219-618daed75204.png)
The task in the middle uses slot field - and if a slot doesn't exist, then it's created automatically - that is how it works according to my tests and to what info I could found on the internet
So yes, you are right - when I deploy to a new slot for the first time - the slot doesn't exist and the stop task has all the rights to fail. So I tried to set a checkbox continue on error for stop-task
![image](https://cloud.githubusercontent.com/assets/510086/18908301/680f298c-856f-11e6-9edc-d2fb95f6e8bb.png)
But after the second tasks deploys to a slot - I suppose the slot must exists already so the start task shouldn't fail - but it does fail with the same message
I checked the slot exists after I deploy to it - I can open the site in a browser
I stop and start site for deploying because sometimes the deployment fails with a message saying that some files are in use and cannot be updated

**Comment by ittennull** [comment]
Hmm...
I guess I found out the problem
There are two modes in azure: classic and ARM
This deployment task(second task) works in classic mode and it creates slots in classic mode! Slots created in one mode are not visible to the other - that's why start task still doesn't see it even after it was created

**Comment by asiffermann** [comment]
I'm not sure this is the real problem. In fact, ARM or Classic are mostly ways to connect to your subscription, but one slot is created on the WebApp, so you should see it anyway in ARM.

I suppose that it's more about the provisionning delay: the slot may not be immediately available after the deployment task created it. So we could implement retry policies for our tasks, or a special awaiter task which would try to get informations about a slot being created.

By the way, we are interested in your use case: is there any reason why you couldn't create the deployment slot before?
We are using the same Blue-Green deployment approach, and we always have our staging slot ready for the next deployment.

I explained that in several blog posts that might interest you:

- http://geeklearning.io/a-successful-azure-web-app-deployment-process/
- http://geeklearning.io/an-easier-successful-azure-web-app-deployment-process-from-vsts/
- http://geeklearning.io/the-9-steps-to-deploy-your-aspnet-core-10-application-to-azure-from-vsts/ (this one could be useful if you are going to use the Azure RM deployment task to deploy a .Net Core app, as there is a little trick to know)

**Comment by ittennull** [comment]
Thanks for the links, I will defenitely read them! Looks like the tutorials and explanations I was missing when I started all this.

I also suspected it was a delay problem and I should have waited some time after creating a slot before trying to start it. I tried to wait for several minutes - and then start the slot - same error message.

Why I cannot precreate slots? We decided to try implement deployment-per-feature. It means that when I want to develop a new feature I create a branch, commit to it and then push it to VSTS. VSTS starts creating build and then deploy it. But we don't want to deploy all branches to the same environment (because they overwrite each other) and we don't want to create slots per each branch manually and then somehow tell VSTS where to deploy. 
Instead VSTS automatically sees from what barnch the build was created and then creates a slot with the name of the branch and deploy to this slot. 
It's good because we can all work on our own branches and do not intersect in any way, also testers can test it separately. After the a feature is done and tested - it's merged to main branch

I fixed my deploying now - I added a new powershell task before deploying tasks. This new task creates the slot for the branch (New-AzureRMWebAppSlot). Now start/stop tasks work fine. Looks like "Azure web app deployment task" (which is classic) don't mind working with slots created in ARM mode.

I noticed that when I call New-AzureRMWebAppSlot - it creates slots that I can see portal.azure.com
If "Azure web app deployment task" creates slot - I cannot see it in portal.azure.com (but it exists - I can open it in browser) and if I try to create a slot with the same name in portal.azure.com - it says that this slot already exists. So portal.azure.com doesn't let me create a new slot with the same name as what "Azure web app deployment task" created even though portal.azure.com doesn't show me that created slot - it show me empty list.

**Comment by sandorfr** [comment]
@ittennull very interesting use case of slot creation. 

Just to satisfy my curiosity, I wonder how do you deal with the 5 slots limit on standard tier. Do you switch the crazy expensive one, or do you spawn new web apps as needed? and how do you cleanup deprecated slots?

@asiffermann `Ensure Slot Creation` task might be interesting to add.

**Comment by ittennull** [comment]
Ha-ha
I didn't know it!
We never used slots before and we didn't have this problem.
Now I can see it - only 5 slots available. I will ask our guys if we can go to premium tier (20 slots) which is unlikely it seems to me...
If premium tier is not an option then the whole idea is doomed ((
We should have thought about any limitations before

Regarding removing old slots - we have a script that is scheduled to run in VSTS everyday at night, it takes all slots from azure, it takes all _feature_ branches from Git and it compares them. If some feature was completed and merged to main branch, then feature branch is deleted. The script sees that there is a slot named "Feature1" but there is no git branch with same name - then script removes the slot
